version: "2"
run:
  timeout: 900s
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - asasalint
    - mnd
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - exhaustruct
    - forcetypeassert
    - funlen
    - gocognit
    - godox
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - interfacebloat
    - ireturn
    - maintidx
    - makezero
    - musttag
    - nakedret
    - nestif
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - tagliatelle
    - testpackage
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra:
        group-params: true
linters-settings:
  errcheck:
    check-blank: true
  gci:
    sections:
      - standard
      - default
  gosec:
    excludes:
      - G115
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
      - composites
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
        disabled: false
        arguments:
          - allowTypesBefore: "testing.TB,*testing.T,*testing.B,*testing.F"
      - name: context-keys-type
      - name: dot-imports
      - name: empty-block
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: increment-decrement
      - name: indent-error-flow
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: time-naming
      - name: unexported-return
      - name: unreachable-code
      - name: var-declaration
      - name: var-naming
  lll:
    line-length: 140
issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - dupword
        - errcheck
        - exhaustive
        - goconst
        - gosec
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
