version: "2"
run:
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - asasalint
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - importas
    - interfacebloat
    - ireturn
    - maintidx
    - makezero
    - mnd
    - musttag
    - nakedret
    - nestif
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - tagliatelle
    - testpackage
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    errcheck:
      check-blank: true
    gosec:
      excludes:
        - G115
    govet:
      disable:
        - fieldalignment
        - shadow
        - composites
      enable-all: true
    lll:
      line-length: 140
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
          arguments:
            - allowTypesBefore: testing.TB,*testing.T,*testing.B,*testing.F
          disabled: false
        - name: context-keys-type
        - name: dot-imports
        - name: empty-block
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
        - name: increment-decrement
        - name: indent-error-flow
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: var-declaration
        - name: var-naming
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupword
          - errcheck
          - exhaustive
          - goconst
          - gosec
        path: _test\.go$
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
