name: run linter and unit tests on each commit

on:
  push:
    branches: 
      - main
    paths:
      - '**/**.go'
  pull_request:
    paths:
      - '**/**.go'
      - 'Makefile'
      - '.github/workflows/lint-test.yml'

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libnlopt-dev

    - name: Run lint
      run: make lint

    - name: Run unit tests
      run: make test